version: '3.9'
services:
  backend:
    build: ./backend
    container_name: checklist_backend
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate --noinput &&
             DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD python manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: checklist_frontend
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    container_name: checklist_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

  db:
    image: busybox
    container_name: checklist_db
    volumes:
      - ./backend/db_data:/data
    command: tail -f /dev/null
